eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  application:
    name: configer
  cloud:
    config:
      server:
        native:
          search-locations:
server:
  port: 8081
